### ISSUE TITLE
Pushing a Notification Error

### ISSUE THREAD

**Issue by harshamv** [Kandiie/pushbots#6]
I have the following error 

```
NameError at /

uninitialized constant Brands::DashboardController::PushBots
```

My Code

```
Pushbots.configure do |config|
      config.application_id = '576f85c0asdasdas4a9efae0348b456a'
      config.application_secret = '8cd428csadasdasdas4b8053b6c9ff7868694a72160'
    end

    push = PushBots::One.new(:android, "9495851398", "Hi I am Renil", "true")
    push.send # Delivers the notification
```

**Comment by cesarrdz** [comment]
Hello harshamv.

It looks like rails is looking for Pushbots at Brands::DashboardController, have you tried requiring the gem in your file or checking your config files?

Can you tell me a little bit more about your project structure or can we look at your projects code to replicate this error?

config information should go at:
config/initializers/pushbots.rb

**Comment by cesarrdz** [comment]
config information should go at:

# config/initializers/pushbots.rb

**Comment by harshamv** [comment]
this is my structure 
**config/initializers/pushbots.rb**

```

Pushbots.configure do |config|
      config.application_id = '576f85c0asdasdas4a9efae0348b456a'
      config.application_secret = '8cd428csadasdasdas4b8053b6c9ff7868694a72160'
    end
```

in my /app/controllers/brands/dashboard_controller.rb

```
push = PushBots::One.new(:android, "9495851398", "Hi I am Renil", "true")
push.send # Delivers the notification
```

When i run the Dashboard index action i am getting the error

> NameError at /
> 
> uninitialized constant Brands::DashboardController::PushBots

Do i need to do any require in the **config/initializers/pushbots.rb** ??

**Comment by cesarrdz** [comment]
It seems I made that small mistake in the docs, I will fix it right now.

Change:

push = PushBots::One.new(:android, "9495851398", "Hi I am Renil", "true")

for 

push = Pushbots::One.new(:android, "9495851398", "Hi I am Renil", "true")

Can you change it and tell me if it is working please?

**Comment by harshamv** [comment]
DAMN!!!!! 
Thanks a lot :)

One more thing i noticed. At times we wont know if the device is ios or android. so usually we use [0,1,2] for platform even for single push. that seems to be not support.

```
curl -X POST \
-H "x-pushbots-appid: 576f85c0efae0348b4456a" \
-H "x-pushbots-secret: 8cd4294a721610" \
-H "Content-Type: application/json" \
-d '{ "platform" : [0,1,2] ,  "token" : "9495851398" ,  "msg" : "aaa-------" ,  "sound" : "true" }' \
https://api.pushbots.com/push/one
```

**Comment by cesarrdz** [comment]
Pushbots is based on Pushbots REST API, and the platform is a required field by it, you can check it here:

https://pushbots.com/developer/docs/api-PushOne

and here:

https://pushbots.com/developer/docs/api-batch_push
platform Required (String)

0 for iOS.
1 for Android
2 for Chrome

We suggest to store the device type and that way you will always know what platform it belongs to in case you are sending to a specific device.

Documentation has been fixed for the Pushing notification error issue, the gem will be updated to accept chrome as a platform, if you continue having issues or I did not understand correctly the platform issue please open a new issue with a little bit more information and we will fix it as soon as possible.

Have a nice day!
